config/routes.rb
Twitter::Application.routes.draw do
  root :to => "twitter#index"

  match "index" => "twitter#index", :as => :index, :via => :get
  
  match "tweets" => "twitter#tweets", :as => :tweets, :via => :get
  match "tweets" => "twitter#guardar", :as => :guardar, :via => :post

end

app/models/palabra.rb
# encoding: UTF-8
class Palabra
	include DataMapper::Resource
	include	DataMapper::Timestamps

	property :id, 		Serial
	property :word, 	String, :required => true

	has n, :tweets

	timestamps :at
end

app/models/tweet.rb
# encoding: UTF-8
class Tweet
	include DataMapper::Resource
	include	DataMapper::Timestamps

	property :id, 			Serial
	property :user_name, 	String
	property :text, 	 	String, :length => 200
	property :image, 		String, :length => 200

	belongs_to :palabra

	timestamps :at
end

app/controllers/application_controller.rb
require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery
end

app/controllers/twitter_controller.rb
# encoding: UTF-8
require 'twitter_search'

class TwitterController < ApplicationController
	def index
		# Formulario
	end

	def tweets
		# Muestra los tweets
		cliente = TwitterSearch::Client.new 'Buscar tweets'
		@palabra = params[:busqueda][:word]
		@tweets = cliente.query :q => @palabra, :result_type => "recent", :rpp => '10'
	end

	def guardar
		# Guarda todos los datos en la base de datos
		Palabra.transaction do	
			word = Palabra.create params[:busqueda]
			params[:tweets].each do |tweet|
	    		word.tweets.create tweet
			end
		end	
		redirect_to index_path

	rescue DataMapper::SaveFailureError => e
		puts e.message
		puts e.resource.errors.inspect
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Twitter</title>
	<%= stylesheet_link_tag    "bootstrap" %>
	<%= stylesheet_link_tag    "bootstrap.min" %>
	<%= stylesheet_link_tag    "bootstrap-responsive" %>
	<%= stylesheet_link_tag    "bootstrap-responsive.min" %>
	<%= javascript_include_tag "bootstrap" %>
	<%= javascript_include_tag "bootstrap.min" %>
	<%= csrf_meta_tags %>

	 <style type="text/css">
        body {
        	padding-top: 60px;
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }
    </style>

</head>
<body>
	<!-- Nav Bar -->
	<div class="navbar navbar-fixed-top">
	    <div class="navbar-inner">
	        <div class="container-fluid">
	            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </a>
	          
	            <a class="brand" href="http://localhost:3000/index">Script Twitter</a>
	            
	            <div class="nav-collapse">
	                <ul class="nav">
	                    <li><a href="http://localhost:3000/index">Home</a></li>
	                </ul>
	            </div><!--/.nav-collapse -->
	        </div>
	    </div>
	</div>
	<!--    Fin Nav Bar -->
	<%= yield %>

</body>
</html>

app/views/twitter/index.html.erb
<div>
	<h3>Busqueda de Tweets</h3>
</div>

<form class="form-horizontal" method="get" action="<%= tweets_path %>">
    <fieldset>
        <div class="control-group">
            <label class="control-label">Ingrese texto a buscar</label>
            <div class="controls">
                <input class="input-xlarge" type="text" name="busqueda[word]">
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Buscar
            </button>
        </div>
    </fieldset>
</form>

app/views/twitter/tweets.html.erb
<div>
	<h3>Tweets con la palabra "<i><%= @palabra %></i>"</h3>
</div>

<form class="form-horizontal" method="post" action="<%= guardar_path %>">
    <input type="hidden" name="busqueda[word]" value="<%= @palabra %>">
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>#</th>
                <th>Imagen</th>
                <th>Usuario</th>
                <th>Tweet</th>
            </tr>
        </thead>
        <tbody>
            <% @tweets.each_with_index do |item, index| %>
                <tr>
                    <td><%= index + 1 %></td>
                    <td><img src="<%= item.profile_image_url %>"/><input type="hidden" value="<%= item.profile_image_url %>" name="tweets[][image]"></td>
                    <td><%= item.from_user %><input type="hidden" value="<%= item.from_user %>" name="tweets[][user_name]"></td>
                    <td><%= item.text %><input type="hidden" value="<%= item.text %>" name="tweets[][text]"></td>
                </tr>
            <% end %>   
        </tbody>
    </table>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            <i class="icon-ok icon-white"></i>Guardar Tweets
        </button>
     </div>
</form>